package com.crm.models;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "extend_user_basic_info")
public class ExtendUserBasicInfo implements Serializable {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	/**
	 * 
	 */
	private static final long serialVersionUID = -1340755243102391292L;
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@NotNull
	private Long uid;
	@NotNull
	@Size(max = 16)
	@Column(name="invite_code")
	private String invitecode;
	private Integer status;
	@NotNull
	private Long app_id;
	private Integer invite_level;
	@Size(max = 16)
	private String alliance_id;
	@Size(max = 16)
	private String channel_tag;
	private String server;
	@NotNull
	@Size(max = 16)
	private String ip;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(updatable = true)
	@org.hibernate.annotations.CreationTimestamp
	private Date create_ts;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(updatable = true)
	@org.hibernate.annotations.UpdateTimestamp
	private Date update_ts;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUid() {
		return uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getInvite_code() {
		return invitecode;
	}

	public void setInvite_code(String invitecode) {
		this.invitecode = invitecode;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Long getApp_id() {
		return app_id;
	}

	public void setApp_id(Long app_id) {
		this.app_id = app_id;
	}

	public Integer getInvite_level() {
		return invite_level;
	}

	public void setInvite_level(Integer invite_level) {
		this.invite_level = invite_level;
	}

	public String getAlliance_id() {
		return alliance_id;
	}

	public void setAlliance_id(String alliance_id) {
		this.alliance_id = alliance_id;
	}

	public String getChannel_tag() {
		return channel_tag;
	}

	public void setChannel_tag(String channel_tag) {
		this.channel_tag = channel_tag;
	}

	public String getServer() {
		return server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getCreate_ts() {
		return create_ts;
	}

	public void setCreate_ts(Date create_ts) {
		this.create_ts = create_ts;
	}

	public Date getUpdate_ts() {
		return update_ts;
	}

	public void setUpdate_ts(Date update_ts) {
		this.update_ts = update_ts;
	}

} // class User
